# Generated by Django 4.1.6 on 2023-02-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='iconee',
            field=models.CharField(default='', max_length=200),
        ),
    ]
