# Generated by Django 4.1.6 on 2023-05-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0007_administrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerf_name', models.CharField(default='', max_length=70)),
                ('customerl_name', models.CharField(default='', max_length=70)),
                ('mobile_no', models.CharField(default='', max_length=150)),
                ('email_id', models.CharField(default='', max_length=150)),
                ('password', models.CharField(default='', max_length=150)),
                ('address', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
