# Generated by Django 4.1.6 on 2023-05-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0009_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='agency_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
